local M = {

	hp			= 'hp           ',
	cot			= 'cot          ',
	energy		= 'energy    ',
	attack		= 'attack     ',
	dodge		= 'uvertlivost ',
	accuracy	= 'accuracy     ',
	
	head 		= 'head    ',
	neck 		= 'neck    ',
	lshoulder 	= 'l. plecho',
	rshoulder 	= 'r. plecho  ',
	larm 		= 'l. ruka   ',
	rarm 		= 'r. ruka   ',
	lhand 		= 'l. kist ',
	rhand 		= 'p. kist ',
	brest 		= 'grud  ',	
	belt 		= 'poyasnica',
	lhip 		= 'l. bedro ',
	rhip 		= 'r. bedro ',
	lleg 		= 'l. golen   ',
	rleg 		= 'r. golen   ',
	lfoot 		= 'l. stupnya',
	rfoot 		= 'p. stupnya',	
	
	dodged		= 'uvernulsya',
	get_strike  = 'poluchil udar',
	m			= 'm',
	to 			= 'v', 
	blockedBy   = 'zablokirovan',
	fist 		= 'kulak',
	cuirass     = 'кираса',
	helm 		= 'shlem',
	glove       = 'perchatka',
	P  			= 'p',
	iron_glove  = 'jeleznaya perchatka',
	skin_boot   = 'kojaniy sapog',
	get_damage  = '%s poluchil %s udar',
	ogo  		= 'ogo, %s v?she vozmojnogo',
	already_dead= 'uje mertv',
}
	
	
return M